nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ["*"]
    allow_credentials: true
    allow_headers: ["Content-Type", "Authorization"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    max_age: 3600
  paths:
    "^/api/":
      origin_regex: true
      allow_origin: ["*"]
      allow_credentials: true
      allow_headers: ["Content-Type", "Authorization"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
