security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    # Routes publiques (login, register + services publics)
    public:
      pattern: ^/(api/(login|register)|api/public)
      stateless: true
      security: false

    api:
      pattern: ^/api
      stateless: true
      entry_point: jwt
      json_login:
        check_path: /api/login
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
      jwt: ~
      refresh_jwt:
        check_path: /api/token/refresh
        provider: app_user_provider

    main:
      lazy: true
      provider: app_user_provider

  access_control:
    - { path: ^/api/(login|register|token/refresh)$, roles: PUBLIC_ACCESS }
    - { path: ^/public, roles: PUBLIC_ACCESS }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
